### ISSUE TITLE
Concatenation problem

### ISSUE THREAD

**Issue by ThanhNguyenRGU** [mrtrunghieu1/CHARM_Example-MC_Scenarios#1]
(base) C:\Bai_bao_31Jan2018\KTP\Code2\CHARM_Example-MC_Scenarios-master>python demo_evaluation_MC_scenarios.py
Traceback (most recent call last):
  File "demo_evaluation_MC_scenarios.py", line 34, in <module>
    D_train = cur_train if D_train is None else np.concatenate((D_train, cur_train), 0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by vu-luong** [comment]
This bug is due to the wrong data format of CHARM_Example-MC_Scenarios_v3.xlsx. Solved by slightly modifying that file.
